### ISSUE TITLE
map.layers() won't work

### ISSUE THREAD

**Issue by vgeorge** [Esri/node-arcgis#78]
Trying to fetch layers of a Feature Service using code example for docs, but it returns nothing:

``` javascript
var ArcGIS = require('arcgis');
var arcgis = ArcGIS();

arcgis.map('cf11ef6d41044be287e31f5a017f4f96')
.then(function (map) {
  return map.layers()
})
.then(function (layers) {
  console.log(layers)
})
```

**Comment by jgravois** [comment]
i'm still chewing on all this, but when the `map()` method is called we we fire off the metadata request below:
https://www.arcgis.com/sharing/rest/content/items/cf11ef6d41044be287e31f5a017f4f96?f=pjson

in order to make an additional request for the actual webmap [content](https://www.arcgis.com/sharing/rest/content/items/cf11ef6d41044be287e31f5a017f4f96/data?f=pjson), we need to tack on a `layers()` method to the object that is returned, but it looks like that is currently not happening...

the doc says that the map methods are currently ['aspirational'](https://github.com/Esri/node-arcgis/blob/master/doc/index.md#map).  perhaps the translation is, *not yet working*.

**Comment by vgeorge** [comment]
Thanks for the quick answer, I didn't saw it was "aspirational".

**Comment by nikolaswise** [comment]
One day!

**Comment by itrew** [comment]
I know this is super late, but from what I can tell the issue is that the item 'cf11ef6d41044be287e31f5a017f4f96' is a feature service and not a web map, so the layers() method is never added to it. 

https://github.com/Esri/node-arcgis/blob/a875747263633fabefe9d09eaa24bc82047f0275/lib/item/index.js#L20-L21
is triggered instead of 

https://github.com/Esri/node-arcgis/blob/a875747263633fabefe9d09eaa24bc82047f0275/lib/item/index.js#L26-L27
